# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operid', models.IntegerField()),
                ('styleid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styleid', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('critical', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('status', models.IntegerField()),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
