# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_table_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='user',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
    ]
