# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='typename',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
