# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_link_typename'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
