# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_persons_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='operate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('styleid', models.IntegerField()),
            ],
        ),
    ]
